version: 2
jobs:
  lint:
    steps:
      - run: pip install invoke==0.22.1
      - run: inv check

  test:
    steps:
      - run: pip install -r development.txt
      - run: inv testcircle
      - run: cp -r coverage.xml _coverage/* "${CIRCLE_TEST_REPORTS}/"

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test:
