version: 2
jobs:
  dependencies:
    steps:
      - run: pip install -r development.txt

  lint:
    steps:
      - run: inv check

  test:
    steps:
      - run: if [ ! -s .pulled ]; then inv testcircle; fi
      - run: if [ ! -s .pulled ]; then cp -r coverage.xml _coverage/* "${CIRCLE_TEST_REPORTS}/"; fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
          filters:
            branches:
              only:
                - master
                - staging
      - lint
          requires:
            - dependencies
      - test
          requires:
            - lint